#!/bin/bash
# Simple script to check buildings directly via Firebase console

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🏢 CivFit Building Audit (Web Console Method)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  The script had issues with Admin SDK auth."
echo ""
echo "✅ ALTERNATIVE: Use Firestore Console to check buildings:"
echo ""
echo "1. Open Firestore Console:"
echo "   https://console.firebase.google.com"
echo ""
echo "2. Go to: Firestore Database → firestore.googleapis.com"
echo ""
echo "3. Navigate to:"
echo "   users → [select a user] → buildings"
echo ""
echo "4. Look for buildings with gridX or gridY >= 10"
echo ""
echo "Examples of INVALID coordinates:"
echo "   ❌ gridY: 80"
echo "   ❌ gridY: 92"
echo "   ❌ gridY: 100"
echo "   ❌ gridY: 110"
echo ""
echo "Examples of VALID coordinates:"
echo "   ✅ gridX: 0-9, gridY: 0-9"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
